version: "3.7"
services: 
  weblogic:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-dev-8-221103
    user: root
    ports: 
      - "7007:7001"
      - "7092:9002"
    volumes:
      - /home/rohitsharma/stock-holding/properties:/u01/oracle/properties
      - /home/rohitsharma/stock-holding/app:/u01/oracle/user_projects/domains/base_domain/autodeploy
  db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    environment:
      - ORACLE_SID=welcome 
      - ORACLE_PWD=welcome@123
    ports:
      - "1521:1521"
      - "7777:5500" 
     
